# tasks file for mailcatcher
---
- name: install dependencies
  apt:
    name: "{{ mailcatcher_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - mailcatcher-install-dependencies

- name: install mailcatcher (specific version)
  gem:
    name: mailcatcher
    version: "{{ mailcatcher_version }}"
    user_install: false
    executable: "/usr/bin/gem2.{{ mailcatcher_ruby_minor_version }}"
  when: "mailcatcher_version != 'latest'"
  tags:
    - mailcatcher-install-specific

- name: install mailcatcher (latest version)
  gem:
    name: mailcatcher
    state: "{{ mailcatcher_version }}"
    user_install: false
    executable: "/usr/bin/gem2.{{ mailcatcher_ruby_minor_version }}"
  when: "mailcatcher_version == 'latest'"
  tags:
    - mailcatcher-install-latest
