# tasks file for mailcatcher
---
- name: create init script
  template:
    src: etc/init/mailcatcher.conf.j2
    dest: /etc/init/mailcatcher.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mailcatcher
  tags:
    - mailcatcher-service-init

- name: start and enable service
  service:
    name: mailcatcher
    state: started
    enabled: true
  tags:
    - mailcatcher-service-start-enable
