# tasks file for mailcatcher
---
- name: service | systemd | update script
  template:
    src: etc/systemd/system/mailcatcher.j2
    dest: /etc/systemd/system/mailcatcher.service
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart mailcatcher
  tags:
    - mailcatcher-service-systemd-update

- name: service | systemd | reload
  command: systemctl daemon-reload
  when: _update_systemd_script is changed
  tags:
    - mailcatcher-service-systemd-reload
