# tasks file for mailcatcher
---
- name: service | upstart | update script
  template:
    src: "{{ mailcatcher_etc_init_file.lstrip('/') }}.j2"
    dest: "{{ mailcatcher_etc_init_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mailcatcher
  tags:
    - mailcatcher-service-upstart-update
