# tasks file for mailcatcher
---
- name: service | systemd | update script
  template:
    src: "{{ mailcatcher_etc_systemd_file.lstrip('/') }}.j2"
    dest: "{{ mailcatcher_etc_systemd_file }}"
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart mailcatcher
  tags:
    - mailcatcher-service-systemd-update

- name: service | systemd | reload
  systemd:
    daemon_reload: true
  when: _update_systemd_script is changed
  tags:
    - mailcatcher-service-systemd-reload
