# tasks file
---
- name: add group
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
  with_items: "{{ [mailcatcher_group] + mailcatcher_groups }}"
  tags:
    - mailcatcher-user-add
    - mailcatcher-user-add-group

- name: add user
  ansible.builtin.user:
    name: "{{ mailcatcher_user }}"
    system: true
    group: "{{ mailcatcher_group }}"
    groups: "{{ mailcatcher_groups | join(',') }}"
    home: /var/mailcatcher
    shell: /bin/false
  tags:
    - mailcatcher-user-add
    - mailcatcher-user-add-user
